# Generated by Django 4.1.7 on 2023-03-16 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quote",
            name="notes",
        ),
        migrations.AlterField(
            model_name="quote",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quotes",
                to="books.book",
            ),
        ),
    ]
