# Generated by Django 4.1.7 on 2023-03-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0002_remove_quote_notes_alter_quote_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
