# Generated by Django 4.1.7 on 2023-03-20 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0003_quote_notes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quote",
            old_name="notes",
            new_name="note",
        ),
    ]
